// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njgwclvuxrbcvnwldipd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qZ3djbHZ1eHJiY3Zud2xkaXBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NzM3MzMsImV4cCI6MjA2MTA0OTczM30.VxoS-hYbriq4xQsfG7mZmF0PPuEgDWb4njcfwV4EVHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);